server:
  port: 9001
spring:
  application:
    name: village-base
  datasource:
    url: jdbc:mysql://192.168.2.2:3306/village_base?serverTimezone=UTC&characterEncoding=utf-8&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 192.168.2.2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
  instance:
    prefer-ip-address: true #部署到线上时可以模块之间访问

